### ISSUE TITLE
Object.defineProperty() IE8 兼容你是如何处理的？

### ISSUE THREAD

**Issue by wangxingkang** [hmhao/avalon2-webpack2-spa#1]

**Comment by hmhao** [comment]
@wangxingkang 没有处理，defineProperty做的事情avalon已经做了，所以代码里面直接避开或者使用avalon来定义。

要兼容IE8-就不要使用连Polyfill也解决不了的东西。

**Comment by wangxingkang** [comment]
好的 谢谢了
