### ISSUE TITLE
关于组件样式

### ISSUE THREAD

**Issue by iamllitog** [hmhao/avalon2-webpack2-spa#2]
麻烦问下页面组件\普通组件样式如何设置？

**Comment by hmhao** [comment]
两种方式：
1、index.ejs内用link形式引入
```html
<link rel="stylesheet" type="text/css" href="style.css">
```

2、在js源码内使用import或者require引入（这个原来有bug刚修复了）
```javascript
import '@/assets/css/style.css'
```

**Comment by iamllitog** [comment]
采纳了第二种 谢谢～

**Comment by iamllitog** [comment]
在ie7下会报错 是style-loader的问题
对象不支持“querySelector”属性或方法

**Comment by iamllitog** [comment]
5e532836aa2f436adc9dac7470256be694c34ac3

**Comment by hmhao** [comment]
style-loader怎么会在ie7下报错？
style-loader是运行在webpack下，将css加入到页面<style>中，与运行环境无关的

至于你出现对象不支持“querySelector”属性或方法，是因为你的业务代码直接操作style而没有用avalon操作吧？

**Comment by iamllitog** [comment]
https://github.com/webpack-contrib/style-loader/pull/232

**Comment by hmhao** [comment]
ok，学习了
