### ISSUE TITLE
你好，请问，你这个脚手架，是否支持IE8？

### ISSUE THREAD

**Issue by wuxinzhe** [hmhao/avalon2-webpack2-spa#3]
我看你扩展了一些特性，我想知道，这些特性是否支持IE8？因为我也在追求将avalon往Vue的那种构建模式靠近，但是在路由这块遇到了瓶颈，我想知道你的这个实现，在浏览器兼容上，能达到IE8的标准么？多谢了。

**Comment by hmhao** [comment]
支持的
你在ie8- 打开https://hmhao.github.io/avalon2-webpack2-spa 可以看到效果

我这边路由方面用的还是avalon的mmRouter，只是扩展了相关router组件来支持嵌套和异步

**Comment by wuxinzhe** [comment]
不好意思，我这个问题是有点多余，我刚自己开了虚拟机，发现兼容的很完美。
现在这个CLI算是稳定版本么？我想试试

**Comment by wuxinzhe** [comment]
另外还想问，
1-就是通过你这一层封装以后。像$watch，$fire这样的avalone函数，还能用么？
2-我们项目要考虑加入一些第三方的图表库，有的需要直接操作DOM，那经过你这层封装以后，是否能够获取组件的DOM节点？
3-avalone官网文档里写的那种构建组件的方式还能用么？

**Comment by hmhao** [comment]
1-可以的，组件内部的方法上下文（this）都是指向当前vm，如果你想引用其他vm的话可以直接使用avalon.vmodels获取
2-可以的，this.$element就是当前组件的根节点，你也可以使用ref指令来获取，如果是组件内部动态生成的话，那就跟js一样通过getElementXXX来获取
3-可以的，这个项目只是扩展了组件的书写、增加了钩子，最终还是会转换为avalon组件的形式

一些使用说明可以参考https://github.com/hmhao/avalon2-webpack2-spa/wiki

**Comment by wuxinzhe** [comment]
大神我可以抱抱你么？

可以的～
