### ISSUE TITLE
匹配动态路由的时候匹配不上

### ISSUE THREAD

**Issue by CChiaki** [hmhao/avalon2-webpack2-spa#7]
router index.js  63行 匹配动态路由 需要加上规则 不然无法匹配
`	avalon.router.add(route.path, function() {
			for(var i in self.routes) {
				var args = self.routes[i]['path'].match(this.regexp)
				if(args) {
					let route = self.routes[i]
				}
			}
			if(!route) return
`

**Comment by hmhao** [comment]
谢谢修复
