### ISSUE TITLE
我install那个avalon都成功不了

### ISSUE THREAD

**Issue by crystal001** [hmhao/avalon2-webpack2-spa#8]
F:\avalon2-webpack2-spa-master>cnpm install
- [10/40] Installing ajv@^5.0.0[npminstall:get] retry GET http://registry.npm.taobao.org/avalon2/download/avalon2-2.2.9.tgz after 100ms, retry left 4, error: ResponseTimeoutError: Response timeout for 60000ms, GET https://cdn.npm.taobao.org/avalon2/-/avalon2-2.2.9.tgz 200 (connected: true, keepalive socket: false, agent status: {"createSocketCount":12,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":587,"freeSockets":{"registry.npm.taobao.org:443:::::::true:":10},"sockets":{},"requests":{}})
headers: {"server":"Tengine","content-type":"application/octet-stream","content-length":"18345222","connection":"keep-alive","date":"Wed, 13 Sep 2017 08:18:46 GMT","x-oss-request-id":"59B8E9E612058DF222275B3F","accept-ranges":"bytes","etag":"\"83121E73B3CA99516580AAB3E485D56B\"","last-modified":"Tue, 11 Jul 2017 14:23:47 GMT","x-oss-object-type":"Normal","x-oss-hash-crc64ecma":"8468909664135538426","x-oss-storage-class":"Standard","cache-control":"max-age=0, s-maxage=86400","content-md5":"gxIec7PKmVFlgKqz5IXVaw==","x-oss-server-time":"135","via":"cache16.l2cm9[108,304-0,H], cache26.l2cm9[137,0], kunlun9.cn125[0,200-0,H], kunlun6.cn125[0,0]","age":"3983","x-cache":"HIT TCP_MEM_HIT dirn:7:464082047","x-swift-savetime":"Wed, 13 Sep 2017 08:18:46 GMT","x-swift-cachetime":"86400","timing-allow-origin":"*","eagleid":"6a78b50615052947100008395e"}
/ [35/40] Installing domelementtype@1platform unsupported babel-loader@6.4.1 › webpack@2.7.0 › watchpack@1.4.0 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)

**Comment by hmhao** [comment]
是avalon下载不了吗？其他模块能不能下载？
用npm单独下载avalon试试

**Comment by crystal001** [comment]
我们公司的网不行 哎呀呀
