### ISSUE TITLE
关于路由跳转

### ISSUE THREAD

**Issue by crystal001** [hmhao/avalon2-webpack2-spa#9]
你好，我想知道知道这个demo里面有没有 类似vue里面的手动路由跳转带参数  比如vue里面的跳转
this.$router.replace({path:'/regist1'})或者this.$router.push({name:'login'})；比如手动跳转里还可以配参数的
this.$router.replace({path:'/regist1',querry:""})

**Comment by hmhao** [comment]
@crystal001 没有实现，暂时只能通过avalon.router.navigate(hash)实现跳转，hash可以带参数
navigate的说明https://github.com/RubyLouvre/mmRouter
